Space-Travelers-Hub: Overview
Kwaku28/Space-Travelers-Hub pull request #39
Opened 2023-05-19 09:20 UTC by Kwaku28

## This project is required to build a web application for a company that provides commercial and scientific space travel services.

### Overview

- [ ] The Rockets section displays a list of all available SpaceX rockets. Users can book each rocket by clicking the reservation button or cancel the previously made booking.
- [ ] The Missions section displays a list of current missions along with their brief description and participation status. There is also a button next to each mission that allows users to join the selected mission or leave the mission the user joined earlier.
- [ ] The My Profile section displays all reserved rockets and space missions.

## Functions implemented for the web application include the following:

### 1. Configuration & basic setup

- [ ] Create React App.
- [ ] Install [React Redux](https://react-redux.js.org/), [Redux Logger](https://www.npmjs.com/package/redux-logger) and [React Router](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/articles/react_router.md).
- [ ] Downloaded the [free image](https://www.flaticon.com/free-icon/planet_3212567?term=space&page=1&position=19&page=1&position=19&related_id=3212567&origin=style) for the app logo.
- [ ] Created routes and view components: rockets, missions, my profile.
 Used `<NavLink />` for the page navigation links and style active class (underline active navigation link) to indicate which section/page the user is currently on.
- [ ] Created directories for all Redux state slice files: `rockets` and `missions`.

### 2. Redux and Render UI

- [ ] Fetched data upon render from the SpaceX API endpoints.
- [ ] Dispatched an action to store the selected data in the Redux store.
- [ ] Used `useSelector()` Redux Hook to select the state slices and render lists of rockets and missions in corresponding routes
- [ ] Rendered a list of rockets.
- [ ] Rendered a table with the missions' data.
- [ ] When a user clicks the "Reserve rocket" button, an action is dispatched to update the store.
- [ ] When a user clicks the "Join Mission" button, an action is dispatched to update the store.
- [ ] Rockets that have already been reserved show a "Reserved" badge and a "Cancel reservation" button instead of the default "Reserve rocket".
- [ ] Missions that the user has joined already show a badge "Active Member" instead of the default "NOT A MEMBER" and a button "Leave Mission" instead of the "Join Mission" button.
- [ ] Used `filter()` to render a list of all joined missions and reserved rockets on the "MyProfile" page.

Thank you🤝

2023-05-19 12:41 UTC, divinecharlotte requested changes
Hi @TEAM      , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 

- linters are passing 👍 
- Descriptive Pr 👍 
- Descriptive commit messages 👍 



 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️

- [ ] kindly consider writing these for all your components and functions to meet the below requirement
> Technical set up**
> Set up testing libraries(React Testing Library and Jest).
> NOTE: Make sure to add test for all your components and functions.

_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-19 12:41 UTC, divinecharlotte commented on src/Redux/missions/missionsSlice.js
> +      return response.data;
- [ ] Kindly consider dispatching an action  to store the selected data  which are 

```
* mission_id
* mission_name
* description
```

in Redux store
doing so will help you to meet the below requirement
<img width="737" alt="Screen Shot 2023-05-19 at 14 16 35" src="https://github.com/Kwaku28/Space-Travelers-Hub/assets/60146030/2173ec9d-91e0-4ad3-83cf-1e556f35e10e">

2023-05-19 12:41 UTC, divinecharlotte commented on src/components/activeMission.js
> +          <ul key={item.mission_id} className={styles.missionlist}>
- [ ] kindly consider rendering  a list of all joined missions using `filter()` to meet the below requirement 
> Render a list of all joined missions (use filter()).

2023-05-19 16:02 UTC, joel-kalema requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi Team
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @joel-kalema  when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-20 09:17 UTC, elmar8287 approved these changes
Hi, 

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

### Highlights

- All tests passed
<img width="287" alt="Screen Shot 2023-05-20 at 13 16 44" src="https://github.com/Kwaku28/Space-Travelers-Hub/assets/49064106/c022333b-12b1-431a-8f08-71f46f3af55f">


### Optional suggestions

- N.A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

![](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
### Please, remember to tag me (@elmar8287) in your question so I can receive the notification 👍 
![giphy](https://user-images.githubusercontent.com/49064106/180751457-52107e57-31fd-486c-97fe-bcccf4e449af.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-20 09:31 UTC, merged